### ISSUE TITLE
Adapter items disappear on double tap and back press

### ISSUE THREAD

**Issue by VGJohn** [skydoves/Pokedex#1]
Noticed this strange bug when I accidentally double tapped a Pokémon adapter item and immediately press the system back button. The adapter item disappears from the list when the animation finishes. Might be an issue with TransformationLayout?

![Screen_Recording_20200601-133143_1_1](https://user-images.githubusercontent.com/22520267/83410421-4b6aa880-a40e-11ea-9c5a-583c769e2c53.gif)

**Comment by skydoves** [comment]
It's [an issue](https://github.com/material-components/material-components-android/issues/1349) from the material components.
If I have free time I will look around the material & AOSP codes and send issues.
Thank you for your interesting :)

**Comment by VGJohn** [comment]
Ah ok, good to know! The app is great btw, nice work!

**Comment by skydoves** [comment]
@VGJohn 
Resolved as implemented throttling on the onclick listener.
Thank you for your issue :)
