### ISSUE TITLE
5 type arguments expected for interface CommonExtension in build.gradle.kts

### ISSUE THREAD

**Issue by MahabubKarim** [skydoves/Pokedex#170]
**Please complete the following information:**
- Version: v0.0.1
- Device : OnePlus 6T
 
**Describe the Bug:**

private typealias AndroidExtension = com.android.build.api.dsl.CommonExtension<*, *, *, *, *, *>

5 type arguments expected for interface CommonExtension<BuildFeaturesT : BuildFeatures, BuildTypeT : BuildType, DefaultConfigT : DefaultConfig, ProductFlavorT : ProductFlavor, AndroidResourcesT : AndroidResources>

**Expected Behavior:**

The project will build perfectly

**Comment by skydoves** [comment]
Hey @MahabubKarim, which Android Studio do you use? You should use Android Studio Iguana at least to build this project.
