### ISSUE TITLE
InvalidTestClassError on unit tests

### ISSUE THREAD

**Issue by abalta-mobven** [skydoves/Pokedex#21]
Hi, I followed your implementation on my project. In unit test part, I have an error.

org.junit.runners.model.InvalidTestClassError: Invalid test class 'myApplicationID.repository.LoginRegisterServiceTest':
  1. Method sendTokenTest() should be void

My test fun like below;

    @Test
    fun sendTokenTest() = runBlocking {
        val mockData = Response<ResponseBody>(
            error = false,
            message = "OK",
            result = null,
            statusCode = 200,
            errorCode = 0
        )
        val tokenRequest = TokenRequest("+905554443322")
        whenever(service.sendToken(tokenRequest)).thenReturn(mockData)
        repository.sendToken("+905554443322").test {
            assertEquals(expectItem().message, "OK")
            assertNull(expectItem().result)
            assertFalse(expectItem().error)
            assertEquals(expectItem().statusCode, 200)
            assertEquals(expectItem().errorCode, 0)
            expectComplete()
        }

        verify(service, atLeastOnce()).sendToken(tokenRequest)
    }

**Comment by skydoves** [comment]
Hi, @abalta-mobven!
I think you should check Android Studio's Kotlin plugin version. 
Or It seems you are missing something like the below.
```kotlin
  @ExperimentalCoroutinesApi
  @get:Rule
  var coroutinesRule = MainCoroutinesRule()
```
