### ISSUE TITLE
Hilt with dynamic feature + ViewModel + SavedStateHandle

### ISSUE THREAD

**Issue by i-disouki** [skydoves/Pokedex#23]
**Is your feature request related to a problem?**

Yes, Cannot inject the ViewModel into the dynamic feature. [check this](https://github.com/google/dagger/issues/2357)

**Comment by skydoves** [comment]
Hi, you can check this [reference](https://developer.android.com/training/dependency-injection/hilt-multi-module#dfm) for using Hilt in the __feature modules__ project. There is no plan to make dynamic features in this project yet. Thanks!
