### ISSUE TITLE
failed to load pokemon images

### ISSUE THREAD

**Issue by eoqkrskfk94** [skydoves/Pokedex#41]
**Please complete the following information:**
- Library Version [e.g. v1.0.5]
- Affected Device(s) [e.g. Samsung Galaxy s21 with Android 11]
 
**Describe the Bug:**

currently the app cannot load the pokemon images

error:
W/Glide: Load failed for https://pokeres.bastionbot.org/images/pokemon/7.png with size [330x330]
    class com.bumptech.glide.load.engine.GlideException: Failed to load resource
    There was 1 root cause:
    com.bumptech.glide.load.HttpException(Failed to connect or obtain data, status code: -1)

it seems the url (rest api) https://pokeres.bastionbot.org/images/pokemon/ does not work anymore. 

**Expected Behavior:**
it should show the images of the pokemons

**Comment by skydoves** [comment]
👀

**Comment by skydoves** [comment]
#43

**Comment by IgnacioGarcia198** [comment]
Hello, I am using the new url but anyway it is not working for me. I tried loading images from a different site and it is working alright. The url I am using: https://github.com/PokeAPI/sprites/blob/master/sprites/pokemon/other/official-artwork/1.png -> I can access it on the browser, but Glide cannot load this image. 
JFYI: 
I am getting error status 0x80000000
https://github.com/bumptech/glide/issues/4495 seems to be related.
