### ISSUE TITLE
Repository Interface not used?

### ISSUE THREAD

**Issue by diee** [skydoves/Pokedex#48]
Hi! excellent work 👍 
I'm wondering if the implementation of the repository interface in the MainRepository and DetailsRepository is necessary as it is empty.

**Comment by skydoves** [comment]
Hy @diee,
I hope [this answer](https://stackoverflow.com/questions/68172246/why-does-the-author-define-a-blank-interface-in-a-project) might help you :)

**Comment by diee** [comment]
Great, thank you
