### ISSUE TITLE
pokemon types are not displayed properly

### ISSUE THREAD

**Issue by rosariopfernandes** [skydoves/Pokedex#5]
**Please complete the following information:**
- App Version: v1.0.0
- Affected Device(s): LG G5 with Android 8.0
 
**Describe the Bug:**

The pokemon types are not being displayed properly on my device. Here's a screenshot:

![screenshot_vertical](https://user-images.githubusercontent.com/16766726/83797877-92bd9700-a6a3-11ea-9b80-f20ef28a8ab2.png)

~Also, after rotating the device to landscape mode, the types are duplicated:~ (See comment bellow)

![screenshot_horizontal](https://user-images.githubusercontent.com/16766726/83797915-a36e0d00-a6a3-11ea-8b12-680dabbdc50b.png)

**Expected Behavior:**

Expected pokemon types to be displayed exactly like the screenshots on the repo.

**Comment by rosariopfernandes** [comment]
Update: Tested this on a Pixel 2 emulator running Android 8.1 and it is displayed correctly, but the rotation error is still there.

**Comment by npace** [comment]
Similar problem on a Samsung A40 (Android 10):
![image](https://user-images.githubusercontent.com/1901561/84471377-e1fc5c80-ac8d-11ea-98eb-41ab76575161.png)

**Comment by skydoves** [comment]
@npace Hi, could you please run the project again after pulling new commits?

**Comment by rosariopfernandes** [comment]
I can confirm it now works fine after pulling the latest commits. We can close this once @npace confirms it works on his device

**Comment by skydoves** [comment]
This issue seems fixed on the latest commits.
Thank you for contributing issue :)
