### ISSUE TITLE
ListAdapter reset RecyclerView after submitList(Edit)->If you direclty fetch from the network and submit list that will cause this issue 

### ISSUE THREAD

**Issue by Approutines** [skydoves/Pokedex#51]
**Please complete the following information:**
- Library-Version Current Main Branch 
- Affected Device(s) [Redmi Note 8]
 
**Describe the Bug:**
After submitting the list previous list is cleared and new is replacing it. Pagination is not working 
Add a clear description of the problem.
I am using an API when I got a response from the server and submit the result it is resetting the recycler view and moving to position 0 in UI Edit)->If you direclty fetch from the network and submit list that will cause this issue 
**Expected Behavior:**
pagination should work 
A clear description of what you expected to happen.
I want to paginate data from the API and add data to the list and smooth scroll to the end

**Comment by skydoves** [comment]
Hey @Approutines,
As we talked about this, it's not related to this repo.
